import random
import turtle
w = 'white'
b = 'black'
x = 1


  
turtle.speed(10)
turtle.title('Feliz cumpleaños')
turtle.bgcolor(b)
turtle.pencolor(b)
turtle.left(100)
turtle.left(80)
turtle.forward(460)
turtle.pencolor(b)
turtle.right(90)
turtle.forward(400)
turtle.pencolor(w)
turtle.pensize(5)
turtle.right(90)
turtle.forward(100)
turtle.backward(100)
turtle.left(-90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.backward(100)
turtle.left(-90)
turtle.forward(100)
turtle.left(90)
turtle.pencolor(b)
turtle.forward(200)
turtle.pencolor(w)
turtle.forward(70)
turtle.backward(70)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(70)
turtle.backward(70)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.pencolor(b)
turtle.right(90)
turtle.forward(100)
turtle.pencolor(w)
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(100)
turtle.pencolor(b)
turtle.forward(100)
turtle.pencolor(w)
turtle.left(90)
turtle.forward(200)
turtle.pencolor(b)
turtle.right(90)
turtle.forward(100)
turtle.pencolor(w)
turtle.forward(200)
turtle.right(150)
turtle.forward(240)
turtle.right(-150)
turtle.forward(200)
turtle.pencolor(b)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(830)
turtle.pencolor(w)
turtle.right(70)
turtle.forward(50)
turtle.right(20)
turtle.forward(50)
turtle.right(70)
turtle.forward(20)
turtle.right(25)
turtle.pencolor(b)
turtle.forward(200)
turtle.pencolor(w)
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.pencolor(b)
turtle.forward(100)
turtle.pencolor(w)
turtle.right(90)
turtle.forward(100)
turtle.backward(100)
turtle.left(70)
turtle.forward(100)
turtle.left(70)
turtle.forward(100)
turtle.right(99)
turtle.forward(100)
turtle.left(60)
turtle.pencolor(b)
turtle.forward(50)
turtle.pencolor(w)
turtle.left(90)
turtle.forward(100)
turtle.circle(-50)
turtle.right(190)
turtle.forward(50)
turtle.pencolor(b)
turtle.left(90)
turtle.forward(100)
turtle.pencolor(w)
turtle.forward(100)
turtle.pencolor(b)
turtle.right(90)
turtle.forward(200)
turtle.right(85)
turtle.forward(800)
turtle.pencolor(w)
turtle.right(90)
turtle.forward(50)
turtle.backward(50)
turtle.right(90)
turtle.forward(50)
turtle.pencolor(b)
turtle.forward(100)
turtle.pencolor(w)
turtle.forward(50)
turtle.backward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.backward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)

x = 1

while x < 400:
  turtle.speed(60)
  r= random.randint(0, 255)
  g= random.randint(0, 255)
  b= random.randint(0, 255)
  turtle.colormode(255)
  turtle.pencolor(r, g, b)
  turtle.speed(10)
  turtle.forward(5+x)
  turtle.right(91)
  x+=1
turtle.mainloop()

#Solo funciona en powershell